name: python accelerator codes docker deploy

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:

  docker-pyt-acc:
    name: ubuntu python accelerator codes docker
    runs-on: ubuntu-latest

    steps:
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Check username
        run: |
          echo ${{ vars.BOOGERT_DOCKER_USERNAME }} 

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          Username: ${{ vars.BOOGERT_DOCKER_USERNAME }}
          password: ${{ secrets.BOOGERT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sboogert/ubuntu-pyt-acc

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./.github/docker/ubuntu-pyt-acc
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  apptainer-pyt-acc:
    name: ubuntu pyt-acc apptainer
    needs: [docker-pyt-acc]
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        dockerimage: [ubuntu-pyt-acc]

    permissions:
      contents: read
      packages: write  # required for GHCR access

    steps:
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Flatten rftrack containers
        shell: bash
        run: |
          docker pull sboogert/ubuntu-pyt-acc
          docker run -v ${{ github.workspace }}:/tmp bdsim/alma9-apptainer apptainer build ${{ matrix.dockerimage }}.sif docker:sboogert/${{ matrix.dockerimage }}:${{ github.ref_name }}
          du -sh ${{ github.workspace }}/*sif

      - name: Push to GHCR
        run: |
          echo ${{ github.actor }}
          echo ${{ github.repository_owner }}
          echo ${{ github.ref_name }}
          docker run -v ${{ github.workspace }}:/tmp bdsim/alma9-apptainer bash \
          -c "echo ${{ secrets.GITHUB_TOKEN }} | apptainer remote login -u ${{ github.actor }} --password-stdin oras://ghcr.io && \
          apptainer push /tmp/${{ matrix.dockerimage }}.sif oras://ghcr.io/${{ github.repository_owner }}/${{ matrix.dockerimage }}:${{ github.ref_name }}"